/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4cd38dbd-32c4-4eba-b572-c3438d47ce82",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_kXCdVUVyd",
    "aws_user_pools_web_client_id": "7vhlc3ip54dsr4eb1hli6mv7qe",
    "oauth": {}
};


export default awsmobile;
